### ISSUE TITLE
Indenting of `else` inside a match

### ISSUE THREAD

**Issue by zma** [OCamlPro/ocp-indent#110]
The following code is indented by `ocp-indent` as:

```
match list with                                                                 
| [] -> []
| h :: t -> if h > 0 then list
  else t
```

Is it possible to indent the `else` so that it is aligned with the `if` as follows?

```
match list with                                                                 
| [] -> []
| h :: t -> if h > 0 then list                                            
            else t
```

**Comment by william3** [comment]
It is like there are two kinds of behaviors, and the parameter "align_params" could be a candidate to configure between the two.
align_params=never is the default one, as @zma get and as in the example of @AltGr 
align_params=always could match @zma request, if it was implemented
