### ISSUE TITLE
Strange formatting for sexplib

### ISSUE THREAD

**Issue by jordwalke** [OCamlPro/ocp-indent#155]
The following code is indented strangely:

    open Sexplib.Std
    open Sexplib.Conv (* Needed for the sexp_opaque option *)

    let always x = true

    type myType = {
      displayName: string;
      handoffThing: int option with sexp_drop_if(always);
      handoffAnotherThing: int option with sexp_drop_if(always);
    } with sexp

This is what I see:

    open Sexplib.Std
    open Sexplib.Conv (* Needed for the sexp_opaque option *)

    let always x = true

    type myType = {
      displayName: string;
      handoffThing: int option with sexp_drop_if(always);
                                    handoffAnotherThing: int option with sexp_drop_if(always);
    } with sexp

It seems like the `with` token throws the formatting off.

**Comment by AltGr** [comment]
Thanks for reporting !
