### ISSUE TITLE
let%lwt and match%lwt indent too much

### ISSUE THREAD

**Issue by hcarty** [OCamlPro/ocp-indent#169]
ocp-indent 1.5, OCaml 4.02.1, all via opam 1.2.0

When `syntax = lwt` is in use:
```ocaml
let lwt_match x =
  let%lwt y =
        match%lwt x with
        | Some a -> a
        | None -> 0
  in
  Lwt.return y
```
When `syntax = lwt` is not in use I get the expected result:
```ocaml
let lwt_match x =
  let%lwt y =
    match%lwt x with
    | Some a -> a
    | None -> 0
  in
  Lwt.return y
```
Unfortunately issue #158 exists when `syntax = lwt` is not in use.

**Comment by AltGr** [comment]
Indeed, `let%lwt` is added to the keyword list, but `%` was not registered as a keyword char so it didn't work. I am not sure we want to add it though, it would probably be better to just ignore the `%*` suffix in the general case -- if we add it `let%foo` won't be parsed as a let if not specifically declared in an ocp-indent extension.

**Comment by hcarty** [comment]
Ignoring the %-suffix seems like a safe default.  That would be another way to fix issue #158 as well, correct?

**Comment by AltGr** [comment]
Yes, what happened there is that `%` is taken as an operator, therefore in a `a%b let` the `let` is after a closed expression and understood as a top-level let.

**Comment by hcarty** [comment]
Thank you for the quick fix!  Is it reasonably safe to pin ocp-indent's master branch until the next release?

**Comment by AltGr** [comment]
Yes, it's rather low-traffic
