### ISSUE TITLE
No ocp-indent.el installed when installing ocp-indent with OPAM

### ISSUE THREAD

**Issue by MonsieurPi** [OCamlPro/ocp-indent#175]
I installed ocp-indent with OPAM (v. 1.1.1), and I updated .emacs as explained. But when I open a file with emacs, it complained that ocp-indent cannot be loaded:

```
Warning (initialization): An error occurred while loading `/some/path/to/home/.emacs':
File error: Cannot open load file, ocp-indent
```

During the installation, I get the following messages:

```
$ opam install ocp-indent
The following actions will be performed:
 - install ocp-indent.1.5
1 to install | 0 to reinstall | 0 to upgrade | 0 to downgrade | 0 to remove

=-=-= Installing ocp-indent.1.5 =-=-=
Building ocp-indent.1.5:
  ./configure --prefix /some/path/to/home/.opam/4.01.0
  make
Installing ocp-indent.1.5.
[WARNING] share_root is an unknown field in /some/path/to/home/.opam/4.01.0/build/ocp-indent.1.5/ocp-indent.install: is your OPAM up-to-date ?

=-=-= ocp-indent.1.5 information =-=-=

To use from emacs, add the following to your .emacs:
  (add-to-list 'load-path "%{share}%/emacs/site-lisp")
  (require 'ocp-indent)

To use from Vim, add to your .vimrc:
  execute ":source " . "%{share}%/vim/syntax/ocp-indent.vim"
  .
```

Any idea of what is going wrong ?

Of course, we replaced %{share}% by the right path, but this does not help. Moreover, a "find .opam -name ocp-indent.el" gives no result.

Thanks

**Comment by AltGr** [comment]
Ah, this install field is new in OPAM 1.2, you should really upgrade your installation. Since it's the one that is used to install the editor files (under e.g. `share/emacs/ocp-indent`), these didn't get installed.

Otherwise, this is only used in ocp-indent's latest version, so you should be fine installing 1.4.2 instead

**Comment by MonsieurPi** [comment]
Thanks a lot,

I updated to OPAM 1.2.0 and it works perfectly.
