### ISSUE TITLE
Indent after newline lingers

### ISSUE THREAD

**Issue by dsheets** [OCamlPro/ocp-indent#180]
I often hit enter multiple times to make some blank lines in a file. `ocp-indent` will put spaces at the beginning of the last new line I make in preparation for a line of code. Unfortunately, when I intend my new work to end with a blank line, I then move the cursor up a line or more to begin writing. In this case, `ocp-indent` will leave the prefix spaces at the beginning of the last line. It would be nice if these prefix spaces were never produced.

I am aware I could configure my editor to never save trailing spaces but I prefer to have my editor highlight trailing spaces to reduce my diff footprint on code bases without good trailing space hygiene.

**Comment by AltGr** [comment]
I think that's up to the editor : the behaviour you describe for multiple newlines is implemented in emacs, not ocp-indent (what ocp-indent does is indent on empty lines only when you indent a single line range, or ask explicitely. But disabling that would prevent TAB from working on an empty line).

Maybe you have `electric-indent-mode` turned on ? (Disabling it does _not_ prevent indenting on _e.g._ prefix `|`)

**Comment by dsheets** [comment]
Hmm... indeed `electric-indent-mode` was somehow on (and not specified in my `.emacs`).

Do you know if it's straightforward to automatically indent on empty lines after the first character is typed? Maybe it is a bad idea, I don't know. Just turning off `electric-indent-mode` mostly satisfies me.

**Comment by pszilagyi** [comment]
FYI, electric-indent-mode was recently turned on by default in Emacs
itself.  I believe it was in 24.4.

**Comment by dbuenzli** [comment]
Le jeudi, 30 avril 2015 à 20:44, pszilagyi a écrit :
> FYI, electric-indent-mode was recently turned on by default in Emacs
> itself. I believe it was in 24.4.

Yes I confirm, I had to disable it aswell.  

Daniel
