### ISSUE TITLE
vim plugin misses copyright notice

### ISSUE THREAD

**Issue by josch** [OCamlPro/ocp-indent#182]
The new vim plugin introduced in pull request #150 is a complete rewrite by Christopher Zimmerman.

It is missing a copyright notice so we cannot know under which license Christopher is sharing this code.

It would also be useful to add a contact email to the license field.

Can somebody who was contacted by Christopher ( @AltGr ?) clarify the situation with Christopher, asking them to provide a copyright header with all the necessary information (license, name, email)?

As it is, ocp-indent cannot be distributed by Debian anymore.

**Comment by AltGr** [comment]
Ah, sorry for the oversight; Christopher has directly agreed to me that his plugin may be distributed under the existing ocp-indent license.

**Comment by josch** [comment]
Okay, thanks! Should I just write "Christopher Zimmerman" as the copyright holder or is there also an email?

**Comment by AltGr** [comment]
Not sure he wants his address public, so let's just put his name for now. Thanks!
