### ISSUE TITLE
Avoid indentation of `fun`.

### ISSUE THREAD

**Issue by dbuenzli** [OCamlPro/ocp-indent#188]
@drup wants to be able to write:

``` ocaml
val f : t1 -> t2 -> t3
let f x y z = ...
```

at which @chris00 responds you can write:

``` ocaml
let f : t1 -> t2 -> t3 =
  fun x y z -> ...
```

which I'd gladly use (e.g. in blog posts I write things like @drup but then it makes the code not easily copy pastable in bulk). However I'm sad to loose what is going to be likely 4 columns (assuming the function spans more than one line). Would it be possible to avoid the `fun` indentation ?

``` ocaml
let f : t1 -> t2 -> t3 =
fun x y z -> ...
```

(at which point you realize github's syntax higlighting is indentation aware)

**Comment by Drup** [comment]
In practice when doing gadt things, you are forced to write it like that, so yes, that would be nice.

**Comment by Chris00** [comment]
FWIW, [Tuareg](https://github.com/ocaml/tuareg) indents it like:
```ocaml
let f : t1 -> t2 -> t3 =
  fun x y z ->
  xxx
```
so you do not have a 4 columns indent.

**Comment by dbuenzli** [comment]
I miss this (non)indentation rule a lot.

**Comment by dbuenzli** [comment]
Thanks !
