### ISSUE TITLE
Expression sequences after match cases

### ISSUE THREAD

**Issue by dariusf** [OCamlPro/ocp-indent#193]
Expression sequences after match cases are indented inconsistently:
```ocaml
match fork () with
| 0 ->
   retransmit stdin sock;
  shutdown sock SHUTDOWN_SEND;
  exit 0
| _ ->
   retransmit sock stdout;
  close stdout;
  wait () ;;
```
Is this a bug? I looked through the failing test cases but didn't see anything exactly the same.

**Comment by AltGr** [comment]
This should never happen. My guess is that your file may contain tab characters.

**Comment by dariusf** [comment]
Figured out the problem: Emacs wasn't properly set up to use ocp-indent. It worked fine when invoked directly. Thanks for the response!
