### ISSUE TITLE
commented params

### ISSUE THREAD

**Issue by william3** [OCamlPro/ocp-indent#199]
Hello, using ocp-indent 1.5.1, I get the following : 
```
let _ =
  foo b
              (* c *) (d);
```

instead of 
```
let _ =
  foo b
  (*c*) (d);
```

or even better : 
```
let _ =
  foo b
    (*c*) (d);
```

This code may seems strange. Atually I have many more parameters, and inside () I get some basic operations like (a -. b)

**Comment by AltGr** [comment]
Ah, funny bug indeed. It seems that the comment is aligned to the following element (comments require look-ahead for indentation), so that you get e.g.:
```
let _ =
  foo b
    (* c *)
    (d);
```

but here the next elements counts the length of the comment, which makes the comment shift right by its own length.

Thanks for reporting!
