### ISSUE TITLE
Fix location of semicolon in record when the semicolon is alone on its line (Janestreet style)

### ISSUE THREAD

**Issue by mbarbin** [OCamlPro/ocp-indent#209]
Example:

```ocaml
let f () =
  { a = int
      ; <- this semicolon
```
This is currently indents the ';' below the 'a' char as in:

```ocaml
let f () =
  { a = int
    ;
```
We would like it to be aligned under the open curly bracket:

```ocaml
let f () =
  { a = int
  ;
```

The main reason for being attached to this is so we can turn on electric mode for that case in emacs and have the semicolon aligned automatically as soon as the user types it.

**Comment by AltGr** [comment]
Note that the behaviour makes sense outside of records, because we want:

```
let f () =
  print_endline "a"
  ;
  print_endline "b"
```

where unindenting would be ugly. An exception should be added when within a record.

**Comment by OCamlPro-Henry** [comment]
Is #210 working for you ?

**Comment by mbarbin** [comment]
I tested it in emacs this morning with electric mode enabled, and it is aligning it as intended.  Thank you for the fix. :+1:
