### ISSUE TITLE
Incorrect indentation of ppx

### ISSUE THREAD

**Issue by rgrinberg** [OCamlPro/ocp-indent#216]
Take the following snippet taken from ppx_deriving:

``` ocaml
let core_type_of_decl ~options ~path type_decl =
  let typ = Ppx_deriving.core_type_of_type_decl type_decl in
  Ppx_deriving.poly_arrow_of_type_decl
    (fun var -> [%type: [%t var] -> [%t var] -> Ppx_deriving_runtime.bool])
    type_decl
    [%type: [%t typ] -> [%t typ] -> Ppx_deriving_runtime.bool]
```

ocp-indent indents it to be:

``` ocaml

let core_type_of_decl ~options ~path type_decl =
  let typ = Ppx_deriving.core_type_of_type_decl type_decl in
  Ppx_deriving.poly_arrow_of_type_decl
    (fun var -> [%type: [%t var] -> [%t var] -> Ppx_deriving_runtime.bool])
type_decl
  [%type: [%t typ] -> [%t typ] -> Ppx_deriving_runtime.bool]
```

The expected result for me is that the original indentation is correct and should be preserved.

**Comment by bmillwood** [comment]
Looks superficially similar to a test case I have:

    module A = struct
      let x = 1

      let%bench_fun "now" [@indexed i = List.range 0 (List.length zones)] =
        let time = now () in
        fun () -> of_time time ~zone

      let x = 2
    end

which, under ocp-indent, becomes:

    module A = struct
      let x = 1

      let%bench_fun "now" [@indexed i = List.range 0 (List.length zones)] =
    let time = now () in
    fun () -> of_time time ~zone

    let x = 2
    end

**Comment by AltGr** [comment]
Apparently the `->` (in the first example) and `=` (in the second) make ocp-indent's stack pop out of the `[% ]` / `[@ ]` blocks. I'll check.
