### ISSUE TITLE
ocp-indent doesn't compile under 4.03.0

### ISSUE THREAD

**Issue by UnixJunkie** [OCamlPro/ocp-indent#220]
Cf. https://sympa.inria.fr/sympa/arc/caml-list/2016-05/msg00078.html
for the error

**Comment by lefessan** [comment]
http://opam.ocamlpro.com/builder/html/report-last.html says the contrary. The mail is about ocp-indent, not ocp-index, no ?

**Comment by AltGr** [comment]
Yes, it's ocp-index. which is another dependency of ocaml-top. There is a branch dedicated to 4.03, though, so until we release the new version,

    opam pin ocp-index git+https://github.com/OCamlPro/ocp-index.git#4.03

should temporarily fix the issue.

**Comment by UnixJunkie** [comment]
Sorry for my mistake, and thanks for the fix for the user.
