### ISSUE TITLE
Mention cmdliner as compile prequesite

### ISSUE THREAD

**Issue by bschommer** [OCamlPro/ocp-indent#228]
Currently ocaml and ocp-build are mentioned as compile prequesite.

**Comment by lefessan** [comment]
`cmdliner` is already listed in the `opam` file as a dependency. Where should it be added ?

**Comment by bschommer** [comment]
On the site:
https://www.typerex.org/ocp-indent.html

**Comment by dbuenzli** [comment]
These kind of things quickly get outdated you should simply link to the `deps` field of the opam file in the repo.

**Comment by bschommer** [comment]
.
