### ISSUE TITLE
Understand precedence better

### ISSUE THREAD

**Issue by rgrinberg** [OCamlPro/ocp-indent#236]
Here's a recent bug that I caused recently:

https://github.com/mirage/ocaml-conduit/pull/191/commits/ff0ef4e40d5161eab5db100251b77ed5c0e1184d

It would be nice if ocp-indent could have aligned the `@extra_tags` line with the else statement to help me visualize that this is incorrect.

**Comment by AltGr** [comment]
`ocp-indent` has built-in understanding of the priority of operators for that purpose, and should do exactly that: here is what I get:
```
let tags =
  let extra_tags =
    pkgs
    |> List.map Target.tags
    |> List.flatten in
  [ sprintf "true: %s" (Ocb.tags_of_packages base_findlib)
  ; sprintf "<lib/**>: pp(%s/ppx), config" (Sys.getcwd ())
  ; "true: debug,principal,bin_annot,short_paths,thread,strict_sequence"
  ; "<lib>: include"
  ; "<tests/*>: include"
  ; "<tests/**>: package(lwt.unix), package(tls.lwt), package(ipaddr.unix)"
  ; "<tests/mirage/**>: package(vchan.lwt)" ]
  @ if Flag.has_flag lwt_ssl then ["<tests/unix/**>: package(lwt.ssl)"] else []
                                                                             @ extra_tags
```

Do you have any special settings ? You should in particular not use `align_ops=false` in `.ocp-indent` for this to work (see `ocp-indent --print-conf`).
