### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by hcarty** [OCamlPro/ocp-indent#239]
Could a release from commit 4849905f909aaec03508612a092cfdf520e24984 be made?  That's immediately prior to the cmdliner updates which, while important, break against the latest cmdliner release.

**Comment by hcarty** [comment]
I'm currently pinned to that commit but it would be nice to have 4.04.0 feature support in a formal opam release.

**Comment by dbuenzli** [comment]
@hcarty See https://github.com/ocaml/opam-repository/pull/8651

**Comment by hcarty** [comment]
@dbuenzli Thanks for the pointer!
