### ISSUE TITLE
Local exceptions not properly supported

### ISSUE THREAD

**Issue by mmottl** [OCamlPro/ocp-indent#240]
The following code block in `foo.ml`

```ocaml
let f () =
  let exception Foo in
  raise Foo
```

is indented by `ocp-indent foo.ml` as:

```ocaml
let f () =
  let exception Foo in
raise Foo
```

**Comment by hcarty** [comment]
This was fixed in #235 but no release has been made yet.  You can pin to the `rewind` branch until a release is made though.
