### ISSUE TITLE
Surprising indentation of polymorphic method type

### ISSUE THREAD

**Issue by fpottier** [OCamlPro/ocp-indent#244]
The following code:

```
class virtual map = object
  method visit_expr_node :
    'env 'info_0 'info_1 .
    ('env -> 'info_0 -> 'info_1) ->
    'env -> 'info_0 expr_node -> 'info_1 expr_node =
  assert false
end
```
is turned by `ocp-indent` into this:

```
class virtual map = object
  method visit_expr_node :
    'env 'info_0 'info_1 .
                   ('env -> 'info_0 -> 'info_1) ->
    'env -> 'info_0 expr_node -> 'info_1 expr_node =
    assert false
end
```

which seems weird. Is this behavior intended?

**Comment by AltGr** [comment]
Indeed, this is a bug. Apparently, `ocp-indent` considers `.` as a higher-priority operator than application, as would be the case in an expression, and indents the following part relative to `'info_1`.
Thanks for reporting!
