### ISSUE TITLE
Incorrect Indentation After Non-Argument Attributed Type Declarations

### ISSUE THREAD

**Issue by zepalmer** [OCamlPro/ocp-indent#247]
I am using `ocp-indent` version 1.5.3.  It seems that a type declaration with an attribute will interfere with the indentation of later lines in the file if the attribute has no parameters.  For instance, assume that `a.ml` contains the following:

```ocaml
type t1 = T1 of int [@@stuff];;
type t2 = T2 of int [@@stuff];;
type u1 = U1;;
type u2 = U2;;
type u3 = U3;;
type u4 = U4;;
```

Then `ocp-indent < a.ml` will produce

```ocaml
type t1 = T1 of int [@@stuff];;
    type t2 = T2 of int [@@stuff];;
    type u1 = U1;;
  type u2 = U2;;
  type u3 = U3;;
  type u4 = U4;;
```

In my case, `stuff` is actually `ocaml.unboxed`.

This does not seem to occur when the attribute includes a parameter.  Suppose `b.ml` contains:

```ocaml
type t1 = T1 of int [@@stuff 0];;
type t2 = T2 of int [@@stuff 0];;
type u1 = U1;;
type u2 = U2;;
type u3 = U3;;
type u4 = U4;;
```

Then `ocp-indent < b.ml` will produce the same output as `cat b.ml`.  This is the case I have encountered until now, specifically when `stuff 0` is instead `deriving eq` from [ppx_deriving](https://github.com/whitequark/ppx_deriving).

Based upon the particular behavior of the indentation, this bug *may* be related to #224.

**Comment by AltGr** [comment]
Fixed. Thanks for reporting.

**Comment by zepalmer** [comment]
Thanks for fixing!  :-D
