### ISSUE TITLE
Vim redraw issues

### ISSUE THREAD

**Issue by mmottl** [OCamlPro/ocp-indent#258]
This Vim redraw problem has been around for a while and I always thought it was caused by `tmux` or `iTerm2`.  But after some debugging I managed to narrow it down to `ocp-indent`.  The problem appears with or without `tmux` in either `iTerm2` or `Terminal` on Mac OS X.  My Vim version is 8.0.1203, but it has been happening way before that version, too.  I have removed everything in my `.vimrc` except for OPAM auto-generated entries and `:filetype plugin indent on`.

Here is an example of what I may see (the line break right before the `t` is bogus):
```
let
  let
    le
t     l
```
The moment I redraw in Vim with CTRL-l, I get the expected:

```
let
  let
    let
      l
```

Not sure, but I have the suspicion that typing fast makes the problem happen more frequently.  Does anybody have an idea what's going on and how to fix this?

**Comment by mmottl** [comment]
https://github.com/vim-syntastic/syntastic/issues/822 might be related.  It's indeed possible that typing fast could cause redraw problems with external commands.  Maybe adding a delay or even `redraw` somewhere could help.

**Comment by AltGr** [comment]
Thanks for reporting. This seems annoying indeed.
Could you try with only the basic vim file at https://github.com/OCamlPro/ocp-indent/blob/rewind/tools/ocp-indent.vim loaded ?

**Comment by mmottl** [comment]
I can reproduce the problem with my `.vimrc` not containing more than the following:

```
setlocal indentexpr=GetOcpIndent(v:lnum)

" Indents are cached for the current buffer; they are only re-used when
" indenting lines in sequence and the buffer was unchanged.
let s:indents = []
let s:buffer = -1
let s:tick = -1
let s:lnum = -1

function! GetOcpIndent(lnum)
  if s:buffer == bufnr('') && s:tick == b:changedtick && s:lnum < a:lnum && match(getline(s:lnum + 1, a:lnum - 1),'.') == -1
    " Only use cache if there are only blank lines in-between
    call remove(s:indents, 0, a:lnum - s:lnum - 1)
  else
    " Compute indentation from current line on
    let cmdline = "ocp-indent --numeric --indent-empty --lines " . a:lnum . '-'
    let s:indents = split(system(cmdline, getline('1','$')))
    let s:buffer = bufnr('')
    let s:tick = b:changedtick
  endif
  let s:lnum = a:lnum

  return s:indents[0]
endfunction
```

**Comment by mmottl** [comment]
@LemonBoy Terrific, this seems to be working!  You said it only partially solves the issue.  Could you please explain in what circumstances it won't work?

**Comment by LemonBoy** [comment]
The redraw issue should be completely gone for good with that change, the only issue left is some sluggishness in long files but that's something for another ticket/day.

**Comment by mmottl** [comment]
Good to know, thanks!

@AltGr Could you please add this fix to the distribution?
