### ISSUE TITLE
Improperly Indents inline functions in pipe expressions

### ISSUE THREAD

**Issue by NixGD** [OCamlPro/ocp-indent#263]
Generally, series of pipe operators are indented correctly:

```
let f x =
  x 
  |> (+) 1
  |> (+) 2

let f x =
  x
  |> (fun x -> x + 1)
  |> (+) 2
```
However, removing the parentheses from the secound example messes up the indentation:
```
let f x =
  x
  |> fun x -> x + 1
              |> (+) 2
```

**Comment by AltGr** [comment]
`ocp-indent` is right in this case: the two expressions are not equivalent, and in the last case the pipe applies to `x + 1`, and not to the whole expression. The pipe operator is always aligned with the expression it applies to.

In other words, the first expression parses as:
```
(x |> (fun x -> x + 1)) |> ((+) 2)
```
while the second is
```
x |> (fun x -> (x + 1) |> (+) 2)
```

However, you can mix pipe-chaining and the `fun x ->` syntax: just put the expression on its own line as:
```
let f x =
  x
  |> fun x ->
  x + 1
  |> (+) 2
```
or even:
```
let f x =
  x |> fun x ->
  x + 1 |> fun x ->
  (+) 2 x
```
