### ISSUE TITLE
Indentation bug in version 1.7.0

### ISSUE THREAD

**Issue by OCamlPro-Iguernlala** [OCamlPro/ocp-indent#275]
AFAIK, indentation of `let j = ...` in the example below is not correct:

```
let g x =
  (x * x
     [@ocaml.ppwarning "TODO: blabla"])
  
let h = "I am well indented"
  
let i x =
  x * x
    [@ocaml.ppwarning "TODO: blabla"]
    
    let j = "I am NOT well indented"
```

I also noticed a change in the indentation of code inside a `fun ... ->` wrt version 1.6.1. I don't know if it is wanted:
```
let f =
  (* change with version 1.6.1: indentation of 'fun x' and 'x + 1' are
     now at the same level*)
  fun x ->
  x + 1
```

**Comment by mbarbin** [comment]
I have witnessed the second change as well while trying out 1.7.0.  I'm interested to read about the follow up on that change. +subscribe.

> change with version 1.6.1: indentation of 'fun x' and 'x + 1' are now at the same level.

**Comment by AltGr** [comment]
The first point seems like a regression, I'll look into it. Probably related to #277, and the changes in extension points handling.

The second point is wanted, as per the changelog:
```
* indent the same (1 step) after `let f = fun x ->` and `let f =\n  fun x ->`
```
Thanks for reporting

**Comment by AltGr** [comment]
The OCaml parser indeed has a weird behaviour on these cases, reported as https://caml.inria.fr/mantis/view.php?id=7916
