### ISSUE TITLE
code following variant without constructor shifted to the right

### ISSUE THREAD

**Issue by mbarbin** [OCamlPro/ocp-indent#286]
1.7.0 --config=JaneStreet
```ocaml
type t = |

  let process (update : t) ~f:(_ : t -> unit) : unit =
    match update with
    | _ -> .
;;
```

See how the function following the type definition get shifted to the right.

**Comment by AltGr** [comment]
Yet another new feature I wasn't aware of ^^. Thanks for reporting!
